FROM node:16-alpine

WORKDIR /app

COPY client/package.json .

RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*
RUN npm install --force --legacy-peer-deps

COPY client/ .

EXPOSE 4000
